### ISSUE TITLE
Creator followers are shown incorrectly

### ISSUE THREAD

**Issue by basmasking** [MaskingTechnology/comify#266]
The followers on the profile of the creator are shown incorrectly. It shows the names and the details of the selected profile. But only when the user is watching it's own profile. When watching other profiles, the results are correct.

<img width="675" alt="Screenshot 2024-06-15 at 07 24 17" src="https://github.com/MaskingTechnology/comify/assets/94599650/8cde6b4e-c5dc-429b-b426-31738de9f0d3">

**Comment by petermasking** [comment]
Fixed in #272
