### ISSUE TITLE
Aggregation resilience

### ISSUE THREAD

**Issue by basmasking** [MaskingTechnology/comify#343]
For all aggregates, the data loading now relies on the correctness of the data in the database. This leads to an application error when an item cannot get retrieved.

To make the application more resilient, we want to change the strategy of the aggregates to always return an array of results, regardless of a single item failing in the list. If an item fails, the error must be logged and the item skipped from the list.

**Comment by johnmasking** [comment]
This relates to the following  aggregated functions:
- explore posts
- get recent notifications
- get all posts
- get all posts by creator
- get all posts by follower
- get all reactions by post
- get all relations by follower
- get all relations by following
-
