### ISSUE TITLE
Configure Keycloak

### ISSUE THREAD

**Issue by petermasking** [MaskingTechnology/comify#67]
We want to use Keycloak for at least the development of Comify. A basic setup has been created in issue #6 . Next is to configure Keycloak to match our requirements. These requirements still have to be determined, making this issue a placeholder for now.

**Comment by BasMasking** [comment]
I configured github and Google as Identity provider, and wrote the steps and secret in a document.

**Comment by basmasking** [comment]
github oauth application: https://github.com/settings/applications
