### ISSUE TITLE
Set up shared assets folder

### ISSUE THREAD

**Issue by petermasking** [MaskingTechnology/comify#87]
Currently, all assets are packed by Vite. Besides these static assets, we want to have a dynamic assets folder as well. Vite has a default support for a public folder that:

1. Needs to be placed in the project root folder;
2. The content is copied to the root of the dist folder.

We want / need to set up a dynamic assets folder in the src folder that can be shared by all ends.

**Comment by BasMasking** [comment]
I've read up on Vite and found some documentation about the [public directory](https://vitejs.dev/config/shared-options.html#publicdir). It seems we can change the directory using the `publicDir` value in our vite configuration. But we cannot change the [target location](https://vitejs.dev/guide/assets#the-public-directory).

We might need to create a work-around by [disabling](https://vitejs.dev/config/build-options#build-copypublicdir) the copy of the public dir.

Then we can use a post build-script to copy the `public` folder from the `src` to the `dist` folder. That will work for the  build, but I would need to look into dev mode. And the references to images in the public folder would need to have a parameter value for Vite to leave it alone.

```ts
// Vite will not transform this
const imgUrl = new URL(imagePath, import.meta.url).href
```
